"""add expenses, customer supplier payments, sale purchase payment tracking

Revision ID: c1d09eb01a95
Revises: 29f88a04419d
Create Date: 2026-09-06 15:53:10.423392

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c1d09eb01a95'
down_revision: Union[str, None] = '29f88a04419d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('expense_categories',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('business_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('business_id', 'name', name='uq_expense_category_business_name')
    )
    op.create_index(op.f('ix_expense_categories_business_id'), 'expense_categories', ['business_id'], unique=False)
    op.create_table('expenses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('business_id', sa.UUID(), nullable=False),
    sa.Column('category_id', sa.UUID(), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('expense_date', sa.Date(), nullable=False),
    sa.Column('payment_method', sa.String(length=20), nullable=False),
    sa.Column('reference_number', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('amount > 0', name='ck_expense_amount_positive'),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['category_id'], ['expense_categories.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_expenses_business_id'), 'expenses', ['business_id'], unique=False)
    op.create_index(op.f('ix_expenses_category_id'), 'expenses', ['category_id'], unique=False)
    op.create_table('customer_payments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('business_id', sa.UUID(), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('sale_id', sa.UUID(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('payment_date', sa.Date(), nullable=False),
    sa.Column('payment_method', sa.String(length=20), nullable=False),
    sa.Column('reference_number', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('amount > 0', name='ck_customer_payment_amount_positive'),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sale_id'], ['sales.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customer_payments_business_id'), 'customer_payments', ['business_id'], unique=False)
    op.create_index(op.f('ix_customer_payments_customer_id'), 'customer_payments', ['customer_id'], unique=False)
    op.create_index(op.f('ix_customer_payments_sale_id'), 'customer_payments', ['sale_id'], unique=False)
    op.create_table('supplier_payments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('business_id', sa.UUID(), nullable=False),
    sa.Column('supplier_id', sa.UUID(), nullable=False),
    sa.Column('purchase_id', sa.UUID(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('payment_date', sa.Date(), nullable=False),
    sa.Column('payment_method', sa.String(length=20), nullable=False),
    sa.Column('reference_number', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('amount > 0', name='ck_supplier_payment_amount_positive'),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['purchase_id'], ['purchases.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_supplier_payments_business_id'), 'supplier_payments', ['business_id'], unique=False)
    op.create_index(op.f('ix_supplier_payments_purchase_id'), 'supplier_payments', ['purchase_id'], unique=False)
    op.create_index(op.f('ix_supplier_payments_supplier_id'), 'supplier_payments', ['supplier_id'], unique=False)
        # Add payment columns as nullable first because existing
    # sales/purchases already exist in the database.
    op.add_column(
        'purchases',
        sa.Column(
            'amount_paid',
            sa.Numeric(precision=12, scale=2),
            nullable=True
        )
    )
    op.add_column(
        'purchases',
        sa.Column(
            'balance_due',
            sa.Numeric(precision=12, scale=2),
            nullable=True
        )
    )
    op.add_column(
        'purchases',
        sa.Column(
            'payment_status',
            sa.String(length=20),
            nullable=True
        )
    )

    op.add_column(
        'sales',
        sa.Column(
            'amount_paid',
            sa.Numeric(precision=12, scale=2),
            nullable=True
        )
    )
    op.add_column(
        'sales',
        sa.Column(
            'balance_due',
            sa.Numeric(precision=12, scale=2),
            nullable=True
        )
    )
    op.add_column(
        'sales',
        sa.Column(
            'payment_status',
            sa.String(length=20),
            nullable=True
        )
    )

    # Existing records from previous phases are treated as fully paid.
    op.execute(
        "UPDATE purchases "
        "SET amount_paid = total_amount, "
        "balance_due = 0, "
        "payment_status = 'paid'"
    )

    op.execute(
        "UPDATE sales "
        "SET amount_paid = total, "
        "balance_due = 0, "
        "payment_status = 'paid'"
    )

    # Make the columns NOT NULL after existing rows are backfilled.
    op.alter_column(
        'purchases',
        'amount_paid',
        nullable=False
    )
    op.alter_column(
        'purchases',
        'balance_due',
        nullable=False
    )
    op.alter_column(
        'purchases',
        'payment_status',
        nullable=False
    )

    op.alter_column(
        'sales',
        'amount_paid',
        nullable=False
    )
    op.alter_column(
        'sales',
        'balance_due',
        nullable=False
    )
    op.alter_column(
        'sales',
        'payment_status',
        nullable=False
    )    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sales', 'payment_status')
    op.drop_column('sales', 'balance_due')
    op.drop_column('sales', 'amount_paid')
    op.drop_column('purchases', 'payment_status')
    op.drop_column('purchases', 'balance_due')
    op.drop_column('purchases', 'amount_paid')
    op.drop_index(op.f('ix_supplier_payments_supplier_id'), table_name='supplier_payments')
    op.drop_index(op.f('ix_supplier_payments_purchase_id'), table_name='supplier_payments')
    op.drop_index(op.f('ix_supplier_payments_business_id'), table_name='supplier_payments')
    op.drop_table('supplier_payments')
    op.drop_index(op.f('ix_customer_payments_sale_id'), table_name='customer_payments')
    op.drop_index(op.f('ix_customer_payments_customer_id'), table_name='customer_payments')
    op.drop_index(op.f('ix_customer_payments_business_id'), table_name='customer_payments')
    op.drop_table('customer_payments')
    op.drop_index(op.f('ix_expenses_category_id'), table_name='expenses')
    op.drop_index(op.f('ix_expenses_business_id'), table_name='expenses')
    op.drop_table('expenses')
    op.drop_index(op.f('ix_expense_categories_business_id'), table_name='expense_categories')
    op.drop_table('expense_categories')
    # ### end Alembic commands ###
